server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  signerKey: "8cff180c14276fc7ec436c786c2ea0f029c6796b5bc50bbb29f63cb2a10549eb"
  valid-duration: 3600 # second
  refreshable-duration: 36000

spring:
  application:
    name: identity.service

  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    driverClassName: "com.mysql.cj.jbdc.Driver"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

